version: "3.8"
services:
  app1:
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    ports:
      - "8001:8000"
  app2:
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    ports:
      - "8002:8000"
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
