name: CD

on:
  push:
    branches: ["staging", "master"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'prod' || 'staging' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IMAGE_REGISTRY }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}
